# project args
file name: "chexpert6"
caption: "defalt"
device: "cuda:2"

#wandb args
entity : "uichan980202"
project : "DinoAE with chexpert"
dataset : "chexpert"
architecture : "basic Dino + Mem matrix in decoder"

# train args
batch: 8
epoch: 500
learning rate: 0.0001

#model args

