# project args
file name: "chexpert17"
caption: "defalt"
device: "cuda:2"

#wandb args
logging : False
entity : "uichan980202"
project : "DinoAE with chexpert"
dataset : "chexpert"
architecture : "with WGAN"

# train args
batch: 8
epoch: 500
learning rate: 0.0001
AE learning rate: 0.0001

DIS learning rate: 0.0001
DIS loss weight: 0.0001


