# project args
file name: "temp"
caption: "defalt"
device: "cuda:3"

#wandb args
entity : "uichan980202"
project : "DinoAE with chexpert"
dataset : "elip"
architecture : "basic Dino + Mem matrix"

# train args
batch: 8
epoch: 500
AE learning rate: 0.0001

DIS learning rate: 0.0001
DIS loss weight: 0.001


#model args

