# project args
file name: "digit_global3"
caption: "defalt"
device: "cuda:3"

#wandb args
entity : "uichan980202"
project : "DinoAE with digit_global"
dataset : "digit_global"
architecture : "both loss"

# train args
batch: 16
epoch: 500
learning rate: 0.0001

#model args

