# project args
file name: "digit_local10"
caption: "defalt"
device: "cuda:5"

#wandb args
entity : "uichan980202"
project : "DinoAE with digit_local"
dataset : "digit_local"
architecture : "basic Dino + MAE  + mask"

# train args
batch: 16
epoch: 500
learning rate: 0.0001

#model args

