# project args
file name: "elip2"
caption: "defalt"
device: "cuda:1"

#wandb args
entity : "uichan980202"
project : "DinoAE with elip"
dataset : "elip"
architecture : "mask + feature loss"

# train args
batch: 16
epoch: 500
learning rate: 0.0001

#model args

