# project args
file name: "elip9"
caption: "defalt"
device: "cuda:1"

#wandb args
entity : "uichan980202"
project : "DinoAE with elip"
dataset : "elip"
architecture : "add discriminator"

# train args
batch: 16
epoch: 500
AE learning rate: 0.0001

DIS learning rate: 0.0001
DIS loss weight: 0.001

#model args

