# project args
file name: "zhang2"
caption: "defalt"
device: "cuda:1"

#wandb args
entity : "uichan980202"
project : "DinoAE with zhang"
dataset : "zhang"
architecture : "basic Dino + Mem matrix"

# train args
batch: 8
epoch: 500
learning rate: 0.0001

#model args

